# Generated by Django 5.1.4 on 2025-01-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the slider item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description for the slider item')),
                ('image', models.ImageField(help_text='Upload the image for the slider', upload_to='slider_images/')),
                ('link', models.URLField(blank=True, help_text='Optional link for the slider item', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to display or hide the slider')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the slider item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the slider item was last updated')),
            ],
        ),
    ]
