# Generated by Django 5.1.4 on 2025-01-10 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_slider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the card', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the card', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Image for the card', null=True, upload_to='card_images/')),
                ('description', models.TextField(blank=True, help_text='Description or details for the card')),
                ('link', models.URLField(blank=True, help_text='Optional link associated with the card', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to display or hide the card')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the card was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the card was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for the blog post (auto-generated or manually set)', unique=True)),
                ('content', models.TextField(help_text='Main content of the blog post')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the blog post', null=True, upload_to='blog_images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Publication status of the blog post', max_length=10)),
                ('category', models.CharField(blank=True, help_text='Category or tag for the blog post', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date and time of the blog post', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the blog post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the blog post was last updated')),
                ('author', models.ForeignKey(help_text='Author of the blog post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at'],
            },
        ),
    ]
