# Generated by Django 5.1.4 on 2025-01-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_card_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcontainer',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='contentcontainer',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order of this section within the page'),
        ),
    ]
